version: "3"
services:
  client:
    build: ./client
    environment:
      - NEXT_HOST=0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    command: npm run dev
  storybook:
    build: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - 6006:6006
    command: npm run storybook
  server:
    build: ./server
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./server:/go/src/github.com/kagepedia/nextjs_go_mysql/server
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - 3306:3306
    volumes:
      - ./db//my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/data:/var/lib/mysql
      - ./db//sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      command: --innodb-use-native-aio=0
